{
 "title": "Kubernetes/Pods",
 "tags": [
  "Kubernetes",
  "Pod"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{namespace=~\".+\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=\"$pod\", namespace=\"$namespace\"}) by (namespace,pod)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "cache"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "CPU使用量（核）",
   "type": "graph",
   "description": "获取CPU资源使用情况，判断方式现在时刻和一分钟前的数据进行对比。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod)",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod)",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "数据包",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod)",
     "legendFormat": "out"
    },
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod) + sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod) + sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod) + sum(rate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (namespace,pod)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\"}[1m])*1) by (namespace,container)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\"}[1m])*1) by (namespace,container)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "硬盘使用量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_reads_total{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(container_fs_writes_total{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(container_fs_io_current{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace,pod)",
     "legendFormat": "current"
    }
   ]
  }
 ]
}