apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }}-redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.sentinel.port }}
    protocol: TCP
    targetPort: sentinel
  selector:
    release: {{ .Release.Name }}
    app: {{ .Values.clusterName }}-redis