apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis
subjects:
- kind: ServiceAccount
  name: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
