apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-sentinel
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stolon-sentinel
  template:
    metadata:
      labels:
        component: stolon-sentinel
        stolon-cluster: {{ .Values.clusterName }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: stolon
      containers:
      - name: stolon-sentinel
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STSENTINEL_CLUSTER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['stolon-cluster']
          - name: STSENTINEL_STORE_BACKEND
            value: "kubernetes"
          - name: STSENTINEL_KUBE_RESOURCE_KIND
            value: "configmap"
          - name: STSENTINEL_METRICS_LISTEN_ADDRESS
            value: "0.0.0.0:8080"
        ports:
          - containerPort: 8080
