---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }}-rabbitmq-discovery
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
    cluster: {{ .Values.clusterName }}
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: http
  selector:
    app: rabbitmq
    cluster: {{ .Values.clusterName }}
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
    cluster: {{ .Values.clusterName }}
spec:
{{- if .Values.nodePort }}
  type: NodePort
{{- end }}
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: http
  selector:
    app: rabbitmq
    cluster: {{ .Values.clusterName }}