apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: stolon-init
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        # node-role.kubernetes.io/master: ""
      serviceAccountName: stolon
      containers:
      - command:
        - /usr/local/bin/stolonctl 
        - --cluster-name={{ .Values.clusterName }}
        - --store-backend=kubernetes 
        - --kube-resource-kind=configmap 
        - init
        - -y
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: stolon-init