---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: danaos
  name: metallb-config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      {{ .Values.addresses }}
